---
- name: Install Dotfiles
  hosts: all
  connection: local
  roles:
    - role: common
    - role: macos
      when: ansible_os_family == 'Darwin'
    - role: linux
      when:   ansible_os_family == 'Linux'